name: Quality pipeline

on:
  push:
    branches: ["*"]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  quality_pipeline:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DTL_CI_AT }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
