name: Quality pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  quality_pipeline_general:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  quality_pipeline_chromium:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci && npx playwright install --with-deps chromium

      - name: Test
        run: npm run test:chromium

      - name: Report coverage
        uses: codecov/codecov-action@v3

  quality_pipeline_firefox:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci && npx playwright install --with-deps firefox

      - name: Test
        run: npm run test:firefox

  quality_pipeline_webkit:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci && npx playwright install --with-deps webkit

      - name: Test
        run: npm run test:webkit
