name: Prepare 'data-tier-list' release

on:
  push:
    tags:
      - release-*

jobs:
  prepare-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_AT }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install NPM
        run: npm install

      # Bump
      - name: Extract release version
        id: extractVersion
        run: echo "::set-output name=version::$(echo ${GITHUB_REF##*/release-})"

      - name: Delete temporary trigger tag
        run: git push origin --delete release-${{ steps.extractVersion.outputs.version }}

      - name: Bump version to ${{ steps.extractVersion.outputs.version }}
        run: node ./ci/tools/version-utils.js -v ${{ steps.extractVersion.outputs.version }}

      # Build & Verify new version
      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      # Push updated content to remote and Tag version
      - name: Push changes
        run: |
          git fetch
          git config user.email "gullerya@gmail.com"
          git config user.name "object-observer CI"
          git add --all
          git commit -m "update version to ${{ steps.extractVersion.outputs.version }}"
          git push origin HEAD:master

      - name: Tag release
        run: |
          git tag -a v${{ steps.extractVersion.outputs.version }} -m "tag release v${{ steps.extractVersion.outputs.version }}"
          git push origin HEAD:master v${{ steps.extractVersion.outputs.version }}

      - name: Bump master to the next snapshot
        run: |
          node ./ci/tools/version-utils.js -s patch
          npm install
          git fetch
          git config user.email "gullerya@gmail.com"
          git config user.name "object-observer CI"
          git add --all
          git commit -m "update trunc version to the next working patch"
          git push origin HEAD:master
